### ISSUE TITLE
Implement persistent queue layer

### ISSUE THREAD

**Issue by agates** [Podcastindex-org/podping-hivewriter#17]
Currently, we have an in-memory queue used to batch requests before writing to Hive.

We need some kind of persistent queuing layer that can recover from restarts in the case of failure or routine maintenance.  It needs to be compatible with asyncio.  I've looked at [persist-queue](https://github.com/peter-wangxu/persist-queue) for some of this functionality but we may need to add async support or look elsewhere.

**Comment by daveajones** [comment]
I’m using a SQLite file on the front-end. Is that an option?

**Comment by agates** [comment]
Indeed, the library referenced uses SQLIte.  Just hoping to use an existing, well-tested wrapper if I can.  We already have a "queue" and this would be much easier to drop in.

**Comment by agates** [comment]
I think we agreed that we're going to work on combining efforts more closely with the podping.cloud http front end, which already has a persistent queue implementation that works quite well.  Therefore I think this is no longer needed here.
