### ISSUE TITLE
Change operation_id prefixes for character limitations

### ISSUE THREAD

**Issue by agates** [Podcastindex-org/podping-hivewriter#29]
We recently discovered the hive operation_id is limited to 32 characters and have decided to limit the length of the prefix we use.

Currently we use:
* `podping`
* `podping-livetest`
* `podping-startup`

We are changing these to the following, respectively:
* `pp`
* `pplt`
* `ppst`

Using this issue as retroactive documentation and any necessary discussion.

See 170ddef9ba6654b15cb4ec16f4692b93e4f75612

**Comment by brianoflondon** [comment]
I'm in two minds about whether we keep the full 'podping' word for the first one and define Medium Podcast and reason Update as defaults. That would leave old clients working. 

I think it's useful that visual inspection of the Hive blocks has the full word Podping in it.

**Comment by agates** [comment]
Not my fault there is a 32 character limitation.

**Comment by agates** [comment]
As much as I can see the sentiment of backwards compatibility for the default I don't really think it ends up solving the problem long term.  As it is right now, there are only a few consumers (that we know of) who need to change the operation_ids they watch.  The biggest of which (@dave) is already aware of the change.

Maybe we could compromise and keep the full reason in the json schema, but what does that solve?  The most important consumers of podping aren't sitting there watching the blockchain
