### ISSUE TITLE
Startup error catching for bad user input like hive account name doesn't work

### ISSUE THREAD

**Issue by brianoflondon** [Podcastindex-org/podping-hivewriter#33]
Needs some work.

**Comment by agates** [comment]
Mind if we push this to `1.2` since it's not a new issue?

**Comment by brianoflondon** [comment]
I think so, but there might be one small change I can make about malformed Hive account names.

**Comment by brianoflondon** [comment]
I solved this. Working in my latest work.

**Comment by agates** [comment]
Reference the commit or the PR please :)

**Comment by brianoflondon** [comment]
Closed by pull request #32
