### ISSUE TITLE
Need Reason code "ended" for marking the end of a livestream

### ISSUE THREAD

**Issue by brianoflondon** [Podcastindex-org/podping-hivewriter#39]
Need a new reason code `ended` to mark the end of a livestram.

https://podcastindex.social/@agates/107781231322591869

https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#attributes-18

**Comment by agates** [comment]
Will be calling this `liveEnd` to indicate that either the `status` attribute of a `<podcast:liveItem>` has _changed_ from `live` to `ended` **or** a `<podcast:liveItem>` that previously had a `status` attribute of `live` has been _removed_ from the feed entirely.
