### ISSUE TITLE
this should write to a file called failures that can be processed later.

### ISSUE THREAD

**Issue by brianoflondon** [Podcastindex-org/podping-hivewriter#7]
https://github.com/Podcastindex-org/podping-hivewriter/blob/ac914595691aa837ac6a713c57123eb42e65104d/src/podping_hivewriter/podping_hivewriter.py#L397-L397

Repeated failures bubbling up from Beem should be captured. Right now I'm just using a print statement so this output goes to stdout and can be captured with a pipe. I'm sure there is a more sophisticated way, probably writing to a failure log which we can also work out how to parse and resend.

I've tested this by starting up on the testnet with bad credentials. All urls are captured even though none go out.

**Comment by daveajones** [comment]
My preference here would be that failures get written to a “replay” log and then tried again after some period of time and upon startup.

**Comment by agates** [comment]
I plan on adding a persistent queue with something like [persist-queue](https://github.com/peter-wangxu/persist-queue), but might have to add async support to that project.

**Comment by daveajones** [comment]
That's a good idea.  Being able to recover from some kind of "journal" would make this as bulletproof as we could hope for.

**Comment by agates** [comment]
Will track this here: https://github.com/Podcastindex-org/podping-hivewriter/issues/17

**Comment by agates** [comment]
Closing, given my comment in https://github.com/Podcastindex-org/podping-hivewriter/issues/17#issuecomment-1001106520
